### ISSUE TITLE
订阅问题

### ISSUE THREAD

**Issue by honue** [ChisBread/chislash#4]
我这边只要一使用第三方的订阅转换（sub.pet sub.maoxiong.net 品云等等都试了）就会报500状态错误，拿不到节点报文，直接使用机场的订阅链可以订阅成功。不知道是否方便排查问题。不知道是不是cf的原因，我这win客户端直连也能订阅成功的。
![image](https://github.com/ChisBread/chislash/assets/57806936/3277a5d2-3f6e-4614-a9a5-61ab13f8e768)

**Comment by honue** [comment]
感谢作者解决了docker-clash更新订阅的配置麻烦的问题，另外建议作者订阅更新逻辑是否可以改为：每次容器启动时默认更新订阅，而不是对比上次更新时间。

**Comment by ChisBread** [comment]
Hi, 可以使用较低的SUBSCR_EXPR参数，实现每次启动自动更新的需求。
关于订阅失败，因为没有完整的yaml文件参考，所以不能确定是网络问题还是订阅格式兼容问题。
可以提供一下具体配置信息，我有空看看。（记得打码）

**Comment by honue** [comment]
```
curl -s --get \
    --data-urlencode "target=clash" \
    --data-urlencode "url=$SUBSCR_URLS" \
    --data-urlencode "config=$REMOTE_CONV_RULE" \
    "$SUBCONV_URL" > /etc/clash/config.yaml.download
```
&emsp;不知道envinit怎么处理传的环境变量，我也不懂shell，但从这个代码块来看似乎并没有判断`$ENABLE_SUBCONV`的值是否使用subconvert服务。
&emsp;我先说明一下我的使用姿势，麻烦你看看是否正确使用：

1. 这个容器我的用途就是能够一键部署clash和dashboard，能够自动更新订阅，我的订阅链接都是第三方subconvert已经合成好的，并不需要这个集成容器中中的subconvert服务再合成一遍
2. 但是从代码上看，似乎是一股脑的使用容器中的subconvert再次拼接一次订阅url，但是我又没传递相关合并参数，因为我根本用不上这个subconvert服务，然后导致了上述无法下载配置文件的问题。

&emsp;我不知道这是不是我遇到的问题的原因所在

附我使用的docker-compose配置文件
```
version: '3.3'
services:
    chislash:
        volumes:
            - '/volume1/docker/clash:/etc/clash'
        restart: always
        container_name: chislash
        network_mode: host
        environment:
            - IP_ROUTE=0
            - ENABLE_SUBCONV=0
            - LOG_LEVEL=warning
            #机场给的原始订阅，能够正常下载
            - SUBSCR_URLS='https://${Original_SubHost}/api/v1/client/subscribe?token=${Token}' 
            #自己第三方已经生成好的url，无法下载
            - SUBSCR_URLS='https://subscribe.cctv.rip/sub?target=clash&url=https://${Original_SubHost}/api/v1/client/subscribe?token=${Token}&insert=false&config=https://raw.githubusercontent.com/honue/QuantumultX/master/convert_cfg/school.ini' 
        image: 'chisbread/chislash:latest'
```
