### ISSUE TITLE
多个订阅 已经用了 | 但是无法启动

### ISSUE THREAD

**Issue by happytrudy** [ChisBread/chislash#7]
多个订阅 已经用了 | 但是无法启动

**Comment by Tsanfer** [comment]
可能是之前已经更新过一次订阅，后添加多个订阅时，宿主机内的旧有文件没有更新。我是直接删除配置目录下的所有文件后，解决的这个问题。我设置的存放位置映射 `/opt/1panel/apps/chislash:/etc/clash`，关闭容器，删除 `/opt/1panel/apps/chislash` 文件夹下的所有文件，重新新建容器即可。
`docker-compose` 文件配置（非透明传输）：
```
# chislash 代理服务器

version: "3.4"
services:
  chislash:
    image: chisbread/chislash
    container_name: chislash
    # 以下样例中的 "/etc/clash/" 代表容器内目录
    environment:
      - TZ='Asia/Shanghai'       # optional
      # - REQUIRED_CONFIG=<path to required.yaml> # optional 
      # REQUIRED_CONFIG: 不能被覆盖的设置项, 最高优先级 (e.g. /etc/clash/required.yaml)
      # - CLASH_HTTP_PORT='7890'   # optional (default:7890)
      # - CLASH_SOCKS_PORT='7891'  # optional (default:7891)
      # - CLASH_TPROXY_PORT='7892' # optional (default:7892)
      # - CLASH_MIXED_PORT='7893'  # optional (default:7893)
      # - DASH_PORT='8080'         # optional (default:8080) RESTful API端口(对应WebUI http://IP:8080/ui)
      # - DASH_PATH=<path to ui> # optional (default:"/etc/clash/dashboard/public")
      - IP_ROUTE='0'             # optional (default:1) 关闭透明代理(本机透明代理/作为旁路网关)
      - UDP_PROXY='0'            # optional (default:1) 关闭透明代理-UDP转发(需要节点支持)
      - IPV6_PROXY='0'           # optional (default:1) 关闭IPv6透明代理
      - LOG_LEVEL='info'         # optional (default:info) 日志等级
      - ENABLE_SUBCONV='1'       # optional (default:1) 开启本地订阅转换服务, 指定SUBSCR_URLS, 且没有外部订阅转换服务时, 需要为1
      - SUBCONV_URL='http://127.0.0.1:25500/sub'  # optional (default:"http://127.0.0.1:25500/sub") 订阅转换服务地址
      - SUBSCR_URLS='https://v8jun.no-mad-world.club/link/L3nifbqrppTAyMRT?clash=3&extend=1|https://pqjc.site/api/v1/client/subscribe?token=d875dc11a22b390bb7c74630cd24ffdc'         # optional 订阅的节点链接, 多个链接用'|'分隔, 会覆盖原有的config.yaml
      - SUBSCR_EXPR='86400'                       # optional (default:86400) 订阅过期时间(秒), 下次启动如果过期, 会重新订阅
      # - REMOTE_CONV_RULE=<URL of remote rule>   # optional (default:⬇️) 订阅转换规则
      # REMOTE_CONV_RULE: 默认使用内部服务提供的链接 "http://127.0.0.1:8091/ACL4SSR/Clash/config/ACL4SSR_Online_Full.ini"
      # 在浏览器打开 http://< 服务器IP >:8092/ACL4SSR/Clash/config/ 即可查看内部服务支持的规则列表
      - EXPORT_DIR_PORT='8092'
      - EXPORT_DIR_BIND='0.0.0.0'
      - NO_ENGLISH='true'        # optional (default:true) 提醒自己这玩意主要是国人用
      - PREMIUM='false'         # optional (default:false) 使用闭源版本内核
    ports:
      - "7890-7893:7890-7893"
      - "8080:8080"
      - "8092:8092"
    volumes:
      - /opt/1panel/apps/chislash:/etc/clash # required config.yaml的存放路径
      # - /dev:/dev                   # optional 用于自动挂载TPROXY模块
      # - /lib/modules:/lib/modules   # optional 用于自动挂载TPROXY模块
    # network_mode: "host"            # required 如果开启IP_ROUTE, 则必须是host
    # privileged: true                # required 如果开启IP_ROUTE, 则必须是true
    restart: unless-stopped
```

**Comment by Tsanfer** [comment]
可能是之前已经更新过一次订阅，后添加多个订阅时，宿主机内的旧有文件没有更新。我是直接删除配置目录下的所有文件后，解决的这个问题。我设置的存放位置映射关系为： `/opt/1panel/apps/chislash:/etc/clash`，关闭容器，删除 `/opt/1panel/apps/chislash` 文件夹下的所有文件，重新新建容器即可。
`docker-compose` 文件配置（非透明传输）：
```
# chislash 代理服务器

version: "3.4"
services:
  chislash:
    image: chisbread/chislash
    container_name: chislash
    # 以下样例中的 "/etc/clash/" 代表容器内目录
    environment:
      - TZ='Asia/Shanghai'       # optional
      # - REQUIRED_CONFIG=<path to required.yaml> # optional 
      # REQUIRED_CONFIG: 不能被覆盖的设置项, 最高优先级 (e.g. /etc/clash/required.yaml)
      # - CLASH_HTTP_PORT='7890'   # optional (default:7890)
      # - CLASH_SOCKS_PORT='7891'  # optional (default:7891)
      # - CLASH_TPROXY_PORT='7892' # optional (default:7892)
      # - CLASH_MIXED_PORT='7893'  # optional (default:7893)
      # - DASH_PORT='8080'         # optional (default:8080) RESTful API端口(对应WebUI http://IP:8080/ui)
      # - DASH_PATH=<path to ui> # optional (default:"/etc/clash/dashboard/public")
      - IP_ROUTE='0'             # optional (default:1) 关闭透明代理(本机透明代理/作为旁路网关)
      - UDP_PROXY='0'            # optional (default:1) 关闭透明代理-UDP转发(需要节点支持)
      - IPV6_PROXY='0'           # optional (default:1) 关闭IPv6透明代理
      - LOG_LEVEL='info'         # optional (default:info) 日志等级
      - ENABLE_SUBCONV='1'       # optional (default:1) 开启本地订阅转换服务, 指定SUBSCR_URLS, 且没有外部订阅转换服务时, 需要为1
      - SUBCONV_URL='http://127.0.0.1:25500/sub'  # optional (default:"http://127.0.0.1:25500/sub") 订阅转换服务地址
      - SUBSCR_URLS='https://xxx|https://yyy'         # optional 订阅的节点链接, 多个链接用'|'分隔, 会覆盖原有的config.yaml
      - SUBSCR_EXPR='86400'                       # optional (default:86400) 订阅过期时间(秒), 下次启动如果过期, 会重新订阅
      # - REMOTE_CONV_RULE=<URL of remote rule>   # optional (default:⬇️) 订阅转换规则
      # REMOTE_CONV_RULE: 默认使用内部服务提供的链接 "http://127.0.0.1:8091/ACL4SSR/Clash/config/ACL4SSR_Online_Full.ini"
      # 在浏览器打开 http://< 服务器IP >:8092/ACL4SSR/Clash/config/ 即可查看内部服务支持的规则列表
      - EXPORT_DIR_PORT='8092'
      - EXPORT_DIR_BIND='0.0.0.0'
      - NO_ENGLISH='true'        # optional (default:true) 提醒自己这玩意主要是国人用
      - PREMIUM='false'         # optional (default:false) 使用闭源版本内核
    ports:
      - "7890-7893:7890-7893"
      - "8080:8080"
      - "8092:8092"
    volumes:
      - /opt/1panel/apps/chislash:/etc/clash # required config.yaml的存放路径
      # - /dev:/dev                   # optional 用于自动挂载TPROXY模块
      # - /lib/modules:/lib/modules   # optional 用于自动挂载TPROXY模块
    # network_mode: "host"            # required 如果开启IP_ROUTE, 则必须是host
    # privileged: true                # required 如果开启IP_ROUTE, 则必须是true
    restart: unless-stopped
```
